version: '3'

services:
  extratoclube:
    build: ./services/extratoclube
    command: gunicorn -w 4 server:app -b :80

  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - extratoclube